// 由 apply_code_ref2.py 自动生成
// 验证 entry id -> 代码位置映射
// 当代码改动时,跑这个脚本重新生成

use std::collections::HashMap;

pub fn get_code_refs() -> HashMap<String, String> {
    let mut m = HashMap::new();
    m.insert("a_shares_specific".to_string(), "A 股特殊规则".to_string());
    m.insert("accrual_ratio".to_string(), "src/indicators/fundamental.rs::accrual_ratio".to_string());
    m.insert("ad_line".to_string(), "src/indicators/breadth.rs::adl_one_bar".to_string());
    m.insert("adl".to_string(), "src/indicators/volume.rs::adl".to_string());
    m.insert("adr".to_string(), "src/indicators/volatility.rs::adr".to_string());
    m.insert("advance_decline_line".to_string(), "src/indicators/breadth.rs::adl_one_bar".to_string());
    m.insert("alligator".to_string(), "src/indicators/ma.rs::alligator".to_string());
    m.insert("alpha".to_string(), "src/indicators/statistics.rs::alpha".to_string());
    m.insert("altman_z".to_string(), "src/indicators/fundamental.rs::altman_z".to_string());
    m.insert("amplitude".to_string(), "src/indicators/volatility.rs::true_range - 自计算".to_string());
    m.insert("anchored_vwap".to_string(), "src/indicators/volume.rs::vwap - 锚定".to_string());
    m.insert("arbr".to_string(), "src/indicators/momentum.rs::ar".to_string());
    m.insert("aroon".to_string(), "src/indicators/trend.rs::aroon".to_string());
    m.insert("aroon_strategy".to_string(), "src/indicators/trend.rs::aroon - 函数".to_string());
    m.insert("asset_turnover".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("atr".to_string(), "src/indicators/volatility.rs::atr".to_string());
    m.insert("atr_percent".to_string(), "src/indicators/volatility.rs::atr - 自计算".to_string());
    m.insert("atr_strategy".to_string(), "src/indicators/volatility.rs::atr - 函数".to_string());
    m.insert("auto_pattern".to_string(), "src/indicators/extra.rs::detect_pattern".to_string());
    m.insert("awesome".to_string(), "src/indicators/momentum.rs::awesome_oscillator".to_string());
    m.insert("awesome_oscillator".to_string(), "src/indicators/momentum.rs::awesome_oscillator".to_string());
    m.insert("backtestengine_summary".to_string(), "src/engine.rs::BacktestEngine".to_string());
    m.insert("bank_nim".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::net_debt_to_ebitda".to_string());
    m.insert("bates".to_string(), "需 Bates 模型".to_string());
    m.insert("bbands".to_string(), "src/indicators/volatility.rs::bollinger_bands".to_string());
    m.insert("bbi".to_string(), "src/indicators/ma.rs::bbi".to_string());
    m.insert("beneish_m".to_string(), "src/indicators/shareholder.rs::beneish_m_score".to_string());
    m.insert("beta".to_string(), "src/indicators/statistics.rs::beta".to_string());
    m.insert("bias".to_string(), "src/indicators/ma.rs::bias".to_string());
    m.insert("bid_ask_spread".to_string(), "src/broker.rs::SimulatedBroker - resolve_fill_price".to_string());
    m.insert("binomial_tree".to_string(), "src/indicators/options.rs - 自实现".to_string());
    m.insert("bollinger".to_string(), "src/strategy.rs::BollingerBandsStrategy".to_string());
    m.insert("bollinger_bands".to_string(), "src/indicators/volatility.rs::bollinger_bands".to_string());
    m.insert("bollinger_strategy".to_string(), "src/strategy.rs::BollingerBandsStrategy".to_string());
    m.insert("bollinger_strategy_summary".to_string(), "src/strategy.rs::BollingerBandsStrategy".to_string());
    m.insert("bop".to_string(), "src/indicators/momentum.rs::bop".to_string());
    m.insert("breadth_thrust".to_string(), "src/indicators/breadth.rs::breadth_thrust".to_string());
    m.insert("broker_interface".to_string(), "src/broker.rs::Broker trait".to_string());
    m.insert("broker_summary".to_string(), "src/broker.rs::Broker trait".to_string());
    m.insert("bullish_percent".to_string(), "src/indicators/breadth.rs::bullish_percent_index".to_string());
    m.insert("buy_and_hold".to_string(), "src/strategy.rs::BuyAndHoldStrategy".to_string());
    m.insert("buyback_rate".to_string(), "src/indicators/shareholder.rs::buyback_ratio".to_string());
    m.insert("cagr".to_string(), "src/metrics.rs::compute_metrics".to_string());
    m.insert("calmar".to_string(), "src/metrics.rs::calmar_ratio".to_string());
    m.insert("capture_ratio".to_string(), "src/practice/independent.rs::evaluate".to_string());
    m.insert("cash_conversion_cycle".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("cash_ratio".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 扩展".to_string());
    m.insert("cci".to_string(), "src/indicators/momentum.rs::cci".to_string());
    m.insert("cci_strategy".to_string(), "src/indicators/momentum.rs::cci - 函数".to_string());
    m.insert("cdp".to_string(), "A 股特色".to_string());
    m.insert("cfo_to_net_income".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("chaikin_osc".to_string(), "src/indicators/volume.rs::chaikin_oscillator".to_string());
    m.insert("chaikin_vol".to_string(), "src/indicators/volatility.rs::chaikin_volatility".to_string());
    m.insert("chip_distribution".to_string(), "A 股特色".to_string());
    m.insert("circulating_market_cap".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("cmf".to_string(), "src/indicators/volume.rs::cmf".to_string());
    m.insert("cmo".to_string(), "src/indicators/momentum.rs::cmo".to_string());
    m.insert("co_location".to_string(), "云部署".to_string());
    m.insert("commodities".to_string(), "需商品数据源".to_string());
    m.insert("consensus".to_string(), "src/indicators/fundamental.rs - 需外部分析师数据".to_string());
    m.insert("coppock".to_string(), "src/indicators/momentum.rs::coppock".to_string());
    m.insert("correlation".to_string(), "src/indicators/statistics.rs::correlation".to_string());
    m.insert("cr".to_string(), "src/indicators/momentum.rs::cr".to_string());
    m.insert("crypto_24_7".to_string(), "src/data.rs::HttpFeed - 7×24 公开".to_string());
    m.insert("crypto_specific".to_string(), "src/data.rs::HttpFeed".to_string());
    m.insert("current_ratio".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::current_ratio".to_string());
    m.insert("cvar".to_string(), "src/metrics.rs::var_cvar".to_string());
    m.insert("cvd".to_string(), "src/indicators/volume.rs::adl - 简化".to_string());
    m.insert("d_e".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::debt_to_equity".to_string());
    m.insert("dark_pools".to_string(), "DEX 私有池;中央交易所无".to_string());
    m.insert("data_source".to_string(), "src/data.rs::DataFeed trait".to_string());
    m.insert("days_inventory_outstanding".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("days_payable_outstanding".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("days_sales_outstanding".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("days_to_cover".to_string(), "src/indicators/shareholder.rs::days_to_cover".to_string());
    m.insert("ddx_ddy_ddz".to_string(), "src/indicators/extra.rs - 需扩展 (大单动向)".to_string());
    m.insert("debt_to_assets".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::debt_to_assets".to_string());
    m.insert("delta".to_string(), "src/indicators/options.rs::delta".to_string());
    m.insert("dema".to_string(), "src/indicators/ma.rs::dema".to_string());
    m.insert("demarker".to_string(), "src/indicators/momentum.rs::demarker".to_string());
    m.insert("divergence".to_string(), "通用概念 - 价格 vs 指标".to_string());
    m.insert("dividend_yield".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::dividend_yield".to_string());
    m.insert("dma".to_string(), "src/indicators/trend.rs - 自计算".to_string());
    m.insert("dmi".to_string(), "src/indicators/trend.rs::dmi".to_string());
    m.insert("dmi_adx".to_string(), "src/indicators/trend.rs::dmi".to_string());
    m.insert("donchian".to_string(), "src/indicators/trend.rs::donchian".to_string());
    m.insert("donchian_breakout".to_string(), "src/strategy.rs::DonchianBreakoutStrategy".to_string());
    m.insert("donchian_strategy".to_string(), "src/strategy.rs::DonchianBreakoutStrategy - 函数".to_string());
    m.insert("dpo".to_string(), "src/indicators/momentum.rs::dpo".to_string());
    m.insert("duPont".to_string(), "src/indicators/fundamental.rs::dupont".to_string());
    m.insert("dupont".to_string(), "src/indicators/fundamental.rs::dupont".to_string());
    m.insert("earnings_surprise".to_string(), "src/indicators/fundamental.rs - 需外部财报数据".to_string());
    m.insert("earnings_yield".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::earnings_yield".to_string());
    m.insert("elder_ray".to_string(), "src/indicators/momentum.rs::elder_ray".to_string());
    m.insert("elder_ray_indicator".to_string(), "src/indicators/momentum.rs::elder_ray".to_string());
    m.insert("elder_ray_strategy".to_string(), "src/strategy.rs::ElderRayStrategy".to_string());
    m.insert("elliott_wave".to_string(), "TradingView 工具".to_string());
    m.insert("ema".to_string(), "src/indicators/ma.rs::ema".to_string());
    m.insert("emv".to_string(), "src/indicators/volume.rs::emv".to_string());
    m.insert("eps".to_string(), "src/indicators/fundamental.rs::CompanyFinancials".to_string());
    m.insert("ev_ebit".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 同 ev_ebitda".to_string());
    m.insert("ev_ebitda".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::ev_ebitda_ratio".to_string());
    m.insert("ev_sales".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 同 ev_ebitda".to_string());
    m.insert("exchange".to_string(), "src/data.rs::HttpFeed - 交易所扩展".to_string());
    m.insert("fcf".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 自计算".to_string());
    m.insert("fcf_yield".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 自计算".to_string());
    m.insert("fibonacci_extension".to_string(), "TradingView 工具".to_string());
    m.insert("fibonacci_retracement".to_string(), "TradingView 工具".to_string());
    m.insert("fisher_transform".to_string(), "src/indicators/momentum.rs::fisher_transform".to_string());
    m.insert("footprint".to_string(), "src/indicators/extra.rs - 需扩展 (订单流)".to_string());
    m.insert("force_index".to_string(), "src/indicators/volume.rs::force_index".to_string());
    m.insert("forecast_dispersion".to_string(), "src/indicators/fundamental.rs - 需外部分析师数据".to_string());
    m.insert("forex".to_string(), "需外汇数据源".to_string());
    m.insert("fpga".to_string(), "硬件加速".to_string());
    m.insert("fractal".to_string(), "src/indicators/ma.rs::fractal".to_string());
    m.insert("free_float".to_string(), "src/indicators/shareholder.rs::free_float_ratio".to_string());
    m.insert("futures".to_string(), "Binance USDⓈ-M 永续".to_string());
    m.insert("gamma".to_string(), "src/indicators/options.rs::gamma".to_string());
    m.insert("gann".to_string(), "江恩理论;主观性强".to_string());
    m.insert("garman_klass".to_string(), "src/indicators/volatility.rs - 自实现".to_string());
    m.insert("gex_dex".to_string(), "src/indicators/options.rs - 需 OI".to_string());
    m.insert("goodwill_ratio".to_string(), "src/indicators/shareholder.rs::goodwill_to_equity".to_string());
    m.insert("heikin_ashi".to_string(), "src/indicators/extra.rs::heikin_ashi".to_string());
    m.insert("heston".to_string(), "需 Heston 模型".to_string());
    m.insert("high_frequency".to_string(), "src/data.rs::DataFeed - tick 级扩展".to_string());
    m.insert("historical_vol_full".to_string(), "src/indicators/volatility.rs::historical_volatility".to_string());
    m.insert("historical_volatility".to_string(), "src/indicators/volatility.rs::historical_volatility".to_string());
    m.insert("hma".to_string(), "src/indicators/ma.rs::hma".to_string());
    m.insert("holder_concentration".to_string(), "src/indicators/shareholder.rs::shares_per_holder".to_string());
    m.insert("hurst".to_string(), "src/indicators/statistics.rs::hurst".to_string());
    m.insert("hv".to_string(), "src/indicators/volatility.rs::historical_volatility".to_string());
    m.insert("iceberg_orders".to_string(), "Binance API timeInForce=GTC".to_string());
    m.insert("ichimoku".to_string(), "src/indicators/trend.rs::ichimoku".to_string());
    m.insert("ichimoku_indicator".to_string(), "src/indicators/trend.rs::ichimoku".to_string());
    m.insert("ichimoku_indicator_id".to_string(), "src/indicators/trend.rs::ichimoku".to_string());
    m.insert("ichimoku_strategy".to_string(), "src/strategy.rs::IchimokuStrategy".to_string());
    m.insert("implied_volatility".to_string(), "src/indicators/options.rs::bs_price - 反推".to_string());
    m.insert("industry_pe_compare".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::pe - 扩展".to_string());
    m.insert("information_ratio".to_string(), "src/practice/independent.rs::evaluate".to_string());
    m.insert("inside_outside".to_string(), "src/indicators/extra.rs::detect_inside_outside".to_string());
    m.insert("insider_trading".to_string(), "src/indicators/shareholder.rs - SEC Form 4".to_string());
    m.insert("institution_holding".to_string(), "src/indicators/shareholder.rs - 需 13F".to_string());
    m.insert("institution_holdings".to_string(), "src/indicators/shareholder.rs".to_string());
    m.insert("interest_coverage".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::interest_coverage".to_string());
    m.insert("inventory_turnover".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("iv".to_string(), "src/indicators/options.rs::bs_price".to_string());
    m.insert("iv_percentile".to_string(), "src/indicators/options.rs::iv_percentile".to_string());
    m.insert("iv_rank".to_string(), "src/indicators/options.rs::iv_rank".to_string());
    m.insert("iv_term_structure".to_string(), "src/indicators/options.rs::bs_price - 多到期日".to_string());
    m.insert("k_pattern_doji".to_string(), "src/indicators/extra.rs::detect_pattern".to_string());
    m.insert("k_pattern_engulfing".to_string(), "src/indicators/extra.rs::detect_engulfing".to_string());
    m.insert("k_pattern_hammer".to_string(), "src/indicators/extra.rs::detect_pattern".to_string());
    m.insert("k_pattern_star".to_string(), "src/indicators/extra.rs::detect_star".to_string());
    m.insert("k_pattern_three".to_string(), "src/indicators/extra.rs::detect_pattern".to_string());
    m.insert("kdj".to_string(), "src/indicators/momentum.rs::kdj".to_string());
    m.insert("kdj_strategy".to_string(), "src/strategy.rs::KdjStrategy".to_string());
    m.insert("keltner".to_string(), "src/indicators/trend.rs::keltner".to_string());
    m.insert("klinger".to_string(), "src/indicators/volume.rs::klinger".to_string());
    m.insert("kst".to_string(), "src/indicators/momentum.rs::kst".to_string());
    m.insert("kurtosis".to_string(), "src/indicators/statistics.rs::kurtosis".to_string());
    m.insert("latest_price".to_string(), "src/types.rs::Bar".to_string());
    m.insert("leverage".to_string(), "Binance 杠杆 API".to_string());
    m.insert("limit_up_down".to_string(), "A 股规则".to_string());
    m.insert("linear_regression".to_string(), "src/indicators/statistics.rs::linear_regression".to_string());
    m.insert("linear_regression_full".to_string(), "src/indicators/statistics.rs::linear_regression".to_string());
    m.insert("local_volatility".to_string(), "需局部波动率模型".to_string());
    m.insert("lot_size".to_string(), "A 股规则".to_string());
    m.insert("low_latency".to_string(), "云部署 (AWS/GCP 区域)".to_string());
    m.insert("ma_envelope".to_string(), "src/indicators/trend.rs - 自计算".to_string());
    m.insert("macd".to_string(), "src/indicators/trend.rs::macd".to_string());
    m.insert("macd_strategy".to_string(), "src/strategy.rs::MacdStrategy".to_string());
    m.insert("mass_index".to_string(), "src/indicators/volatility.rs::mass_index".to_string());
    m.insert("max_drawdown".to_string(), "src/metrics.rs::compute_metrics".to_string());
    m.insert("max_drawdown_pct".to_string(), "src/metrics.rs::compute_metrics".to_string());
    m.insert("max_pain".to_string(), "src/indicators/options.rs - 需扩展 OI".to_string());
    m.insert("max_position_pct".to_string(), "src/risk.rs::RiskConfig::max_position_pct".to_string());
    m.insert("mccClellan".to_string(), "src/indicators/breadth.rs::mcclellan_oscillator".to_string());
    m.insert("mcclellan".to_string(), "src/indicators/breadth.rs::mcclellan_oscillator".to_string());
    m.insert("merton".to_string(), "需 Merton 模型".to_string());
    m.insert("mfi".to_string(), "src/indicators/volume.rs::mfi".to_string());
    m.insert("momentum".to_string(), "src/indicators/momentum.rs::roc - 动量".to_string());
    m.insert("money_management".to_string(), "src/portfolio.rs::calc_buy_size - Kelly 公式".to_string());
    m.insert("monte_carlo_options".to_string(), "src/indicators/options.rs - 蒙特卡洛".to_string());
    m.insert("net_debt".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 自计算".to_string());
    m.insert("net_debt_to_ebitda".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::net_debt_to_ebitda".to_string());
    m.insert("new_high_low".to_string(), "src/indicators/breadth.rs::new_high_low_ratio".to_string());
    m.insert("northbound_flow".to_string(), "A 股特色".to_string());
    m.insert("nvi".to_string(), "src/indicators/volume.rs::nvi".to_string());
    m.insert("obv".to_string(), "src/indicators/volume.rs::obv".to_string());
    m.insert("obv_strategy".to_string(), "src/indicators/volume.rs::obv - 函数".to_string());
    m.insert("ohlc".to_string(), "src/types.rs::Bar".to_string());
    m.insert("option_pricing_model".to_string(), "src/indicators/options.rs::bs_price - BS".to_string());
    m.insert("options".to_string(), "src/indicators/options.rs::bs_price - 完整 BS".to_string());
    m.insert("order_flow_trading".to_string(), "src/data.rs::DataFeed - Level 2 扩展".to_string());
    m.insert("order_types".to_string(), "src/types.rs::Order - OrderType 枚举".to_string());
    m.insert("osc".to_string(), "src/indicators/momentum.rs - 自计算".to_string());
    m.insert("pPO".to_string(), "src/indicators/trend.rs - 自计算".to_string());
    m.insert("pairs_spread".to_string(), "src/indicators/statistics.rs - 自实现".to_string());
    m.insert("parabolic_sar".to_string(), "src/indicators/trend.rs::parabolic_sar".to_string());
    m.insert("parkinson".to_string(), "src/indicators/volatility.rs - 自实现".to_string());
    m.insert("payout_ratio".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::payout_ratio".to_string());
    m.insert("pb".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::pb".to_string());
    m.insert("pe".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::pe".to_string());
    m.insert("peg".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::peg".to_string());
    m.insert("percentile_rank".to_string(), "src/indicators/statistics.rs::percentile_rank".to_string());
    m.insert("piotroski".to_string(), "src/indicators/shareholder.rs::piotroski_f_score".to_string());
    m.insert("pitfall_chart_scale".to_string(), "BTC/大波段必须用对数坐标".to_string());
    m.insert("pitfall_divergence".to_string(), "src/indicators/momentum.rs - 通用概念".to_string());
    m.insert("pitfall_golden_cross".to_string(), "src/strategy.rs::SmaCrossStrategy - 金叉滞后".to_string());
    m.insert("pitfall_high_pe".to_string(), "src/indicators/fundamental.rs - 高 PE 需配合 PEG".to_string());
    m.insert("pitfall_industry".to_string(), "src/indicators/fundamental.rs - 跨行业 PE 不可比".to_string());
    m.insert("pitfall_industry_compare".to_string(), "同 pitfall_industry".to_string());
    m.insert("pitfall_low_pe".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::pe - 低 PE 不一定便宜".to_string());
    m.insert("pitfall_main_flow".to_string(), "src/indicators/volume.rs - 主买主卖可伪装".to_string());
    m.insert("pitfall_multi_osc".to_string(), "src/indicators/momentum.rs - 同类指标叠加冗余".to_string());
    m.insert("pitfall_params".to_string(), "src/strategy.rs - 需做参数敏感性分析".to_string());
    m.insert("pitfall_repaint".to_string(), "src/indicators/extra.rs - 形态识别会重画".to_string());
    m.insert("pitfall_rsi".to_string(), "src/strategy.rs::RsiStrategy - RSI 超买强趋势中可长期 >70".to_string());
    m.insert("pitfall_unclosed_bar".to_string(), "src/strategy.rs - 收盘后再看信号".to_string());
    m.insert("pitfall_volume".to_string(), "src/indicators/volume.rs - 放量需结合价格位置".to_string());
    m.insert("pivot_points".to_string(), "src/indicators/extra.rs::pivot_points".to_string());
    m.insert("portfolio_summary".to_string(), "src/portfolio.rs::Portfolio".to_string());
    m.insert("position_sizing".to_string(), "src/portfolio.rs::on_signal".to_string());
    m.insert("ppo_strategy".to_string(), "src/strategy.rs::PpoStrategy".to_string());
    m.insert("ppo_strategy_id".to_string(), "src/strategy.rs::PpoStrategy".to_string());
    m.insert("ps".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::ps".to_string());
    m.insert("psy".to_string(), "src/indicators/momentum.rs::psy".to_string());
    m.insert("put_call_ratio".to_string(), "src/indicators/options.rs::put_call_ratio".to_string());
    m.insert("pvi".to_string(), "src/indicators/volume.rs::pvi".to_string());
    m.insert("pvt".to_string(), "src/indicators/volume.rs::pvt".to_string());
    m.insert("pvt_strategy".to_string(), "src/indicators/volume.rs::pvt - 函数".to_string());
    m.insert("quick_ratio".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::quick_ratio".to_string());
    m.insert("random".to_string(), "src/strategy.rs::RandomStrategy".to_string());
    m.insert("reit_ffo".to_string(), "src/indicators/fundamental.rs - 扩展".to_string());
    m.insert("restricted_shares".to_string(), "src/indicators/shareholder.rs::unlock_market_value".to_string());
    m.insert("revision".to_string(), "src/indicators/fundamental.rs - 需外部分析师数据".to_string());
    m.insert("rho".to_string(), "src/indicators/options.rs::rho".to_string());
    m.insert("risk_control".to_string(), "src/risk.rs::RiskManager".to_string());
    m.insert("riskmanager_summary".to_string(), "src/risk.rs::RiskManager".to_string());
    m.insert("rma".to_string(), "src/indicators/ma.rs::rma".to_string());
    m.insert("roa".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::roa".to_string());
    m.insert("roc".to_string(), "src/indicators/momentum.rs::roc".to_string());
    m.insert("roe".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::roe".to_string());
    m.insert("roic".to_string(), "src/indicators/fundamental.rs::CompanyFinancials - 类似 roe".to_string());
    m.insert("rolling_correlation".to_string(), "src/indicators/statistics.rs::rolling_correlation".to_string());
    m.insert("rsi".to_string(), "src/indicators/momentum.rs::rsi".to_string());
    m.insert("rsi_pitfall_value".to_string(), "src/indicators/momentum.rs::rsi - 超买不等卖出".to_string());
    m.insert("rsi_practical".to_string(), "src/strategy.rs::RsiStrategy - 实战".to_string());
    m.insert("rsi_strategy".to_string(), "src/strategy.rs::RsiStrategy".to_string());
    m.insert("rsi_strategy_summary".to_string(), "src/strategy.rs::RsiStrategy".to_string());
    m.insert("rvi".to_string(), "src/indicators/momentum.rs::rvi".to_string());
    m.insert("rvol".to_string(), "src/indicators/volume.rs - 自计算".to_string());
    m.insert("rvol_volume".to_string(), "src/indicators/volume.rs - 自计算".to_string());
    m.insert("rvol_volume_compat".to_string(), "src/indicators/volume.rs - 自计算".to_string());
    m.insert("sabr".to_string(), "需 SABR 模型".to_string());
    m.insert("securities_investment".to_string(), "src/strategy.rs::BuyAndHoldStrategy".to_string());
    m.insert("share_pledge".to_string(), "src/indicators/shareholder.rs::share_pledge_ratio".to_string());
    m.insert("sharpe".to_string(), "src/metrics.rs::compute_metrics".to_string());
    m.insert("short_interest".to_string(), "src/indicators/shareholder.rs::short_interest_ratio".to_string());
    m.insert("short_selling".to_string(), "src/broker.rs::BrokerConfig::allow_short".to_string());
    m.insert("simulatedbroker_summary".to_string(), "src/broker.rs::SimulatedBroker".to_string());
    m.insert("skew".to_string(), "src/indicators/options.rs::bs_price - 多 strike".to_string());
    m.insert("skewness".to_string(), "src/indicators/statistics.rs::skewness".to_string());
    m.insert("sma".to_string(), "src/indicators/ma.rs::sma".to_string());
    m.insert("sma_cross".to_string(), "src/strategy.rs::SmaCrossStrategy".to_string());
    m.insert("smile".to_string(), "src/indicators/options.rs::bs_price - 多 strike".to_string());
    m.insert("sortino".to_string(), "src/metrics.rs::sortino_ratio".to_string());
    m.insert("spread".to_string(), "src/broker.rs::SimulatedBroker - resolve_fill_price".to_string());
    m.insert("squeeze".to_string(), "src/indicators/volatility.rs::squeeze".to_string());
    m.insert("stamp_duty".to_string(), "A 股规则".to_string());
    m.insert("stoch_rsi".to_string(), "src/indicators/momentum.rs::stochastic_rsi".to_string());
    m.insert("stochastic".to_string(), "src/indicators/momentum.rs::stochastic".to_string());
    m.insert("stochastic_volatility".to_string(), "需 SV 模型".to_string());
    m.insert("stop_loss".to_string(), "src/risk.rs::RiskManager - stop_loss_pct".to_string());
    m.insert("stop_loss_pct".to_string(), "src/risk.rs::RiskConfig::stop_loss_pct".to_string());
    m.insert("supertrend".to_string(), "src/indicators/trend.rs::supertrend".to_string());
    m.insert("supertrend_strategy".to_string(), "src/strategy.rs::SupertrendStrategy".to_string());
    m.insert("support_resistance".to_string(), "TradingView 工具".to_string());
    m.insert("t_plus_1".to_string(), "A 股规则".to_string());
    m.insert("take_profit".to_string(), "src/risk.rs::RiskManager - take_profit_pct".to_string());
    m.insert("take_profit_pct".to_string(), "src/risk.rs::RiskConfig::take_profit_pct".to_string());
    m.insert("tape_reading".to_string(), "src/data.rs::DataFeed - 需扩展 Binance aggTrades".to_string());
    m.insert("target_upside".to_string(), "src/indicators/fundamental.rs::CompanyFinancials::target_upside - 需外部目标价".to_string());
    m.insert("td_sequential".to_string(), "src/indicators/trend.rs::td_sequential".to_string());
    m.insert("tema".to_string(), "src/indicators/ma.rs::tema".to_string());
    m.insert("theta".to_string(), "src/indicators/options.rs::theta".to_string());
    m.insert("tick".to_string(), "src/indicators/breadth.rs::tick_index".to_string());
    m.insert("total_market_cap".to_string(), "src/indicators/fundamental.rs - 自计算".to_string());
    m.insert("total_return".to_string(), "src/metrics.rs::compute_metrics".to_string());
    m.insert("tpo".to_string(), "src/indicators/extra.rs - 需扩展 (时间价格机会)".to_string());
    m.insert("tracking_error".to_string(), "src/practice/independent.rs::evaluate".to_string());
    m.insert("trendline".to_string(), "主观画线;TradingView".to_string());
    m.insert("treynor".to_string(), "src/practice/independent.rs::evaluate".to_string());
    m.insert("trin".to_string(), "src/indicators/breadth.rs::trin".to_string());
    m.insert("trinomial_tree".to_string(), "src/indicators/options.rs - 自实现".to_string());
    m.insert("trix".to_string(), "src/indicators/trend.rs - 自计算".to_string());
    m.insert("true_range".to_string(), "src/indicators/volatility.rs::true_range".to_string());
    m.insert("tsi".to_string(), "src/indicators/momentum.rs::tsi".to_string());
    m.insert("turnover_rate".to_string(), "src/indicators/shareholder.rs::buyback_ratio - 类似".to_string());
    m.insert("ulcer_index".to_string(), "src/indicators/volatility.rs::ulcer_index".to_string());
    m.insert("ultimate".to_string(), "src/indicators/momentum.rs::ultimate_oscillator".to_string());
    m.insert("ultimate_oscillator".to_string(), "src/indicators/momentum.rs::ultimate_oscillator".to_string());
    m.insert("up_down_volume".to_string(), "src/indicators/breadth.rs::up_down_volume_ratio".to_string());
    m.insert("us_stocks_specific".to_string(), "需美股数据源".to_string());
    m.insert("var".to_string(), "src/metrics.rs::var_cvar".to_string());
    m.insert("variance_swap".to_string(), "需方差掉期".to_string());
    m.insert("vega".to_string(), "src/indicators/options.rs::vega".to_string());
    m.insert("vix_option".to_string(), "需 VIX 期权".to_string());
    m.insert("vol_osc".to_string(), "src/indicators/volume.rs::volume_oscillator".to_string());
    m.insert("volatility_swap".to_string(), "需波动率掉期".to_string());
    m.insert("volume_oscillator".to_string(), "src/indicators/volume.rs::volume_oscillator".to_string());
    m.insert("volume_profile".to_string(), "src/indicators/extra.rs - 需扩展 (历史成交分布)".to_string());
    m.insert("volume_ratio".to_string(), "src/indicators/volume.rs::volume_ratio".to_string());
    m.insert("vortex".to_string(), "src/indicators/trend.rs::vortex".to_string());
    m.insert("vortex_strategy".to_string(), "src/strategy.rs::VortexStrategy".to_string());
    m.insert("vr".to_string(), "src/indicators/volume.rs::vr".to_string());
    m.insert("vroc".to_string(), "src/indicators/volume.rs::vroc".to_string());
    m.insert("vwap".to_string(), "src/indicators/volume.rs::vwap".to_string());
    m.insert("vwap_price".to_string(), "src/indicators/volume.rs::vwap".to_string());
    m.insert("vwap_reversion".to_string(), "src/strategy.rs::VwapReversionStrategy".to_string());
    m.insert("vwap_strategy".to_string(), "src/strategy.rs::VwapReversionStrategy".to_string());
    m.insert("vwma".to_string(), "src/indicators/ma.rs::vwma".to_string());
    m.insert("williams_r".to_string(), "src/indicators/momentum.rs::williams_r".to_string());
    m.insert("wma".to_string(), "src/indicators/ma.rs::wma".to_string());
    m.insert("wvad".to_string(), "src/indicators/volume.rs::wvad".to_string());
    m.insert("yang_zhang".to_string(), "src/indicators/volatility.rs - 自实现".to_string());
    m.insert("z_score".to_string(), "src/indicators/statistics.rs::zscore".to_string());
    m.insert("zigzag".to_string(), "src/indicators/trend.rs::zigzag".to_string());
    m.insert("zscore".to_string(), "src/indicators/statistics.rs::zscore".to_string());
    m
}
